version: '2'
services:
  aldea-database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - aldea:/var/lib/mysql
    networks:
      - aldea
  aldea-application:
    build: .
    image: aldea-application
    environment:
      - ALDEA_PORT=3000
      - ALDEA_DATABASE_HOST=database
      - ALDEA_DATABASE_USER=root
      - ALDEA_DATABASE_PASSWORD=root
      - ALDEA_SECRET_KEY_BASE=1f0bef8714009078799cf781b489f5012c625a12dc4478388634af4b784b72c5bd1e3f2630a361af351cfaf5bf84559f818b2796b9fcbc331cfa404a3805cb6f
    ports:
      - "3000:3000"
    depends_on:
      - aldea-database
    networks:
      - aldea
      - aldea-cuenta
volumes:
  aldea:
    external:
      name: neeco_aldea

networks:
  aldea:
    external:
      name: neeco_aldea
  aldea-cuenta:
    external:
      name: neeco_aldea-cuenta
