version: '2'
services:
  aldea-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: aldea_production
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: $ALDEA_DATABASE_USER
      MYSQL_PASSWORD: $ALDEA_DATABASE_PASSWORD
    volumes:
      - aldea:/var/lib/mysql
    networks:
      - aldea
  aldea-application:
    image: registry.neec.xyz/neeco/aldea-application:latest
    environment:
      ALDEA_PORT: 3000
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER:
      ALDEA_DATABASE_PASSWORD:
      ALDEA_SECRET_KEY_BASE:
      CUENTA_URL: http://cuenta-application:4000
      STATIC_URL:
    depends_on:
      - aldea-database
    volumes:
      - public:/app/uploads
    networks:
      - aldea
      - aldea-cuenta

volumes:
  aldea:
    external:
      name: neeco_aldea
  public:
    external:
      name: neeco_public

networks:
  aldea:
    external:
      name: neeco_aldea
  aldea-cuenta:
    external:
      name: neeco_aldea-cuenta
