version: '2'
services:
  aldea-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: aldea_development
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - aldea:/var/lib/mysql
    networks:
      - neeco
  aldea-application:
    image: registry.neec.xyz/dev/aldea-application:latest
    environment:
      ALDEA_PORT: 3000
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER: root
      ALDEA_DATABASE_PASSWORD: root
      ALDEA_SECRET_KEY_BASE: x
      CUENTA_URL: http://cuenta-application:4000/
      IMAGEN_URL: http://imagen-application:8000/
      STATIC_IMAGE_URL: http://localhost/
      RAILS_ENV: development
    depends_on:
      - aldea-database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - neeco

volumes:
  aldea:
    driver: local

networks:
  neeco:
    external:
      name: neeco_develop
