---
system_wide: no

rbenv:
  build_requires:
    spec: [autoconf, gdbm-devel, libffi-devel, libyaml-devel, ncurses-devel, openssl-devel, readline-devel]
    others:
      - bzip2
      - gcc
      - git
      - make
      - perl-Digest-SHA

  install_dir: "{% if system_wide %}/usr/local/src/rbenv/{% else %}{{ ansible_user_dir }}/.rbenv/{% endif %}"

  ruby:
    make_opts: 'CONFIGURE_OPTS="--disable-install-rdoc" MAKE_OPTS="-j {{ ansible_processor_cores }}"'
    install_versions: [2.3.1]
    global: 2.3.1

  gem:
    bundler:
      version: present